# Generated by Django 3.1 on 2020-08-27 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='all_order_log',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order_type', models.IntegerField(verbose_name='订单类别')),
                ('table_id', models.IntegerField(verbose_name='桌号')),
                ('serial', models.BigIntegerField(verbose_name='流水号')),
                ('takeout', models.BigIntegerField(verbose_name='外卖号')),
            ],
            options={
                'verbose_name': '订单-基本信息',
                'db_table': 'all_order_log',
            },
        ),
        migrations.CreateModel(
            name='dish',
            fields=[
                ('dish_id', models.IntegerField(max_length=5, primary_key=True, serialize=False, verbose_name='菜品编号')),
                ('name', models.TextField(max_length=20, verbose_name='菜品名称')),
                ('dish_pic', models.TextField(blank=True, verbose_name='图片')),
                ('time_cost', models.IntegerField(verbose_name='用时')),
                ('dish_type', models.TextField(verbose_name='种类')),
                ('price', models.FloatField(verbose_name='价格')),
                ('success', models.IntegerField(verbose_name='售空状态')),
                ('ingd_cost', models.FloatField(default=1, verbose_name='其他成本')),
            ],
            options={
                'verbose_name': '菜',
                'db_table': 'dish',
            },
        ),
        migrations.CreateModel(
            name='managerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.TextField(verbose_name='用户名')),
                ('password', models.TextField(verbose_name='密码')),
                ('user_type', models.IntegerField(verbose_name='用户类')),
            ],
            options={
                'verbose_name': '管理员',
                'db_table': 'manager_info',
            },
        ),
        migrations.CreateModel(
            name='order_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_id', models.IntegerField(max_length=5, verbose_name='菜品编号')),
                ('count', models.IntegerField(verbose_name='点菜数量')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='下单时间')),
                ('dish_status', models.IntegerField(verbose_name='菜品状态')),
                ('finish_time', models.DateTimeField(auto_now_add=True, verbose_name='完成时间')),
                ('station_id', models.IntegerField(verbose_name='分到的工位号')),
                ('waiting_list', models.IntegerField(verbose_name='等待队列号')),
                ('ingd_cost', models.IntegerField(default=0, verbose_name='其他成本')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.all_order_log')),
            ],
            options={
                'db_table': 'order_detail',
            },
        ),
        migrations.CreateModel(
            name='dish_ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.TextField(max_length=256, verbose_name='原材料名称')),
                ('ingredient_number', models.FloatField(verbose_name='原材料数量')),
                ('dish_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.dish', verbose_name='菜品编号')),
            ],
            options={
                'verbose_name': '菜-原材料',
                'db_table': 'dish_ingredient',
            },
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.CheckConstraint(check=models.Q(time_cost__gte=0), name='time_constraint'),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.CheckConstraint(check=models.Q(ingd_cost__gte=0), name='cost_constraint'),
        ),
        migrations.AddConstraint(
            model_name='dish',
            constraint=models.CheckConstraint(check=models.Q(price__gte=0), name='price_constraint'),
        ),
        migrations.AddConstraint(
            model_name='order_detail',
            constraint=models.CheckConstraint(check=models.Q(ingd_cost__gte=0), name='ingd_cost_constraint'),
        ),
        migrations.AddConstraint(
            model_name='order_detail',
            constraint=models.CheckConstraint(check=models.Q(count__gte=0), name='order_num_constraint'),
        ),
        migrations.AlterUniqueTogether(
            name='order_detail',
            unique_together={('order_id', 'dish_id')},
        ),
        migrations.AddConstraint(
            model_name='dish_ingredient',
            constraint=models.CheckConstraint(check=models.Q(ingredient_number__gte=0), name='ingredient_constraint'),
        ),
    ]
