# Generated by Django 3.1 on 2020-08-29 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_order_choice_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_choice_log',
            name='param',
            field=models.FloatField(default=1, verbose_name='时间流逝关系'),
        ),
    ]
