# Generated by Django 3.1 on 2020-09-01 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_order_choice_log_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='下单时间'),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='finish_time',
            field=models.DateTimeField(auto_now=True, verbose_name='完成时间'),
        ),
    ]
